Add mock sms sender, nothing to do.
casdoor/go-sms-sender pull request #11
Opened 2022-08-10 11:14 UTC by kofj

Signed-off-by: 疯魔慕薇 <kfanjian@gmail.com>

2022-08-10 11:22 UTC, kofj commented
About https://github.com/casdoor/casdoor/issues/1002#issue-1334439744

2022-08-10 15:40 UTC, hsluoyz requested changes

2022-08-10 15:40 UTC, hsluoyz commented on basic.go
> +	MockSMS      = "Mock SMS"
`MockSMS` -> `MockSms`

2022-08-10 15:40 UTC, hsluoyz commented on basic.go
> +
no empty line

2022-08-10 15:40 UTC, hsluoyz commented on mock.go
> +package go_sms_sender
apache header

2022-08-11 02:19 UTC, hsluoyz approved these changes

2022-08-11 02:21 UTC, merged